#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdbool.h>
#include <unistd.h>
#include "views.h"
#include "../modules/gps/gps.h"
#include "../modules/touchscreen/touchscreen.h"
#include "../modules/graphics/graphics.h"
